version: '3.1'

services:
  db:
    image: postgres
    container_name: pg
    ports:
      - 5454:5432
    volumes:
      - ./.initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: example
